/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rocking.the.gradle;

public class Library {
    public static void main(String[] args) {
        System.out.println("Hello world "+args[0]);
    }
    public boolean someLibraryMethod() {
        return true;
    }

    public int add(int first,int second) {
        return first+second;
    }
}
