/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rocking.the.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testAddMethod() {
        Library library = new Library();
        assertEquals(library.add(2,3),4);
    }
}
